# Generated by Django 5.0.6 on 2025-03-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active',
            new_name='status',
        ),
    ]
